/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.disciplinaryactionms;

import java.util.List;
import java.util.Map;
import java.awt.Image;
import java.io.File;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
public class frmAddRecord extends javax.swing.JFrame {
    String selectedImagePath = "";
    String imagePath = "";;
    Map<String, Integer> offensePenalty = new HashMap<>();
    public frmAddRecord() {
        initComponents();
        getRootPane().setDefaultButton(btnSave);
        txtStudentId.addActionListener(e -> txtStudentName.requestFocus());
        scaleImage("C:\\Users\\CL2~PC20\\Downloads\\damsim\\back.png", lblbackg);
     }
    private void scaleImage (String location, JLabel label) {
    ImageIcon icon = new ImageIcon(location);    
    Image img = icon.getImage();
    Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    label.setIcon(scaledIcon);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(30);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new RoundedPanel(30);
        txtStudentId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spnDate = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        cmbOffenseC = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        spnSuspension = new javax.swing.JSpinner();
        btnSave = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmbOffense = new javax.swing.JComboBox<>();
        cmbGrade = new javax.swing.JComboBox<>();
        lblbackg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C L A R K  C O L L E G E");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OF SCIENCE AND TECHNOLOGY");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("___________________________________________________________");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DISCIPLINARY ACTION MONITORING SYSTEM");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 110));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Monthly Record");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Add Record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("LOGOUT");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 660));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIdActionPerformed(evt);
            }
        });
        txtStudentId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStudentIdKeyTyped(evt);
            }
        });
        jPanel4.add(txtStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 51, 153, 39));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Student Id");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 25, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Student Name");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 25, -1, -1));

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 51, 153, 39));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Grande & Section");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 25, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Date of Incident");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 153, -1, -1));

        spnDate.setModel(new javax.swing.SpinnerDateModel());
        jPanel4.add(spnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 179, 153, 39));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Offense Type");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 153, -1, -1));

        cmbOffenseC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minor", "Major" }));
        jPanel4.add(cmbOffenseC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 156, 39));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Days of Suspension");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 264, -1, -1));
        jPanel4.add(spnSuspension, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 293, 153, 37));

        btnSave.setBackground(new java.awt.Color(102, 204, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Record");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 385, 144, 46));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Image");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 264, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 3));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 293, -1, -1));

        jButton5.setBackground(new java.awt.Color(102, 204, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Browse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 264, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Offense Classification");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 153, -1, -1));

        cmbOffense.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Late", "Improper Uniform", "No ID", "Loitering", "Disruptive Behavior", "Using Phone During Class", "Eating Inside Classroom", "Sleeping in Class", "Cutting Classes", "Disrespect to Teacher", "Bullying", "Fighting (Minor)", "Cheating", "Vandalism", "Using Profanity", "Unauthorized Absence", "Physical Assault", "Cyberbullying", "Theft", "Drug Possession", "Smoking Inside Campus", "Alcohol Possession", "Weapon Possession", "Serious Threats" }));
        jPanel4.add(cmbOffense, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 160, 40));

        cmbGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT 12 - A  ", "ICT 12 - B  ", "ICT 12 - C  ", "ICT 12 - D  ", "ICT 12 - E  ", " ", "ICT 11 - A  ", "ICT 11 - B  ", "ICT 11 - C  ", "ICT 11 - D  ", "ICT 11 - E  ", " ", "GAS 12 - A  ", "GAS 12 - B  ", "GAS 12 - C  ", "GAS 12 - D  ", "GAS 12 - E  ", " ", "GAS 11 - A  ", "GAS 11 - B  ", "GAS 11 - C  ", "GAS 11 - D  ", "GAS 11 - E  ", " ", "STEM 12 - A  ", "STEM 12 - B  ", "STEM 12 - C  ", "STEM 12 - D  ", "STEM 12 - E  ", " ", "STEM 11 - A  ", "STEM 11 - B  ", "STEM 11 - C  ", "STEM 11 - D  ", "STEM 11 - E  ", " ", "HUMSS 12 - A  ", "HUMSS 12 - B  ", "HUMSS 12 - C  ", "HUMSS 12 - D  ", "HUMSS 12 - E  ", " ", "HUMSS 11 - A  ", "HUMSS 11 - B  ", "HUMSS 11 - C  ", "HUMSS 11 - D  ", "HUMSS 11 - E  ", " ", "HE 12 - A  ", "HE 12 - B  ", "HE 12 - C  ", "HE 12 - D  ", "HE 12 - E  ", " ", "HE 11 - A  ", "HE 11 - B  ", "HE 11 - C  ", "HE 11 - D  ", "HE 11 - E  ", " ", "ABM 12 - A  ", "ABM 12 - B  ", "ABM 12 - C  ", "ABM 12 - D  ", "ABM 12 - E  ", " ", "ABM 11 - A  ", "ABM 11 - B  ", "ABM 11 - C  ", "ABM 11 - D  ", "ABM 11 - E  " }));
        jPanel4.add(cmbGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 140, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 950, 510));

        lblbackg.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.add(lblbackg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmDashboardAdmin DA = new frmDashboardAdmin();
        DA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIdActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    String studentId = txtStudentId.getText();
    String studentName = txtStudentName.getText();
    String gradeSection = cmbGrade.getSelectedItem().toString();
    String offense = cmbOffenseC.getSelectedItem().toString();
    String suspension = spnSuspension.getValue().toString();
    String offenseC = cmbOffenseC.getSelectedItem().toString();
    java.util.Date date = (java.util.Date) spnDate.getValue();
    java.sql.Timestamp sqlDate = new java.sql.Timestamp(date.getTime());
    String Image = imagePath;
    
   
    if(studentId.isEmpty() || studentName.isEmpty() || gradeSection.isEmpty() || offense.isEmpty() || suspension.isEmpty()|| offenseC.isEmpty()|| imagePath == null) {
    javax.swing.JOptionPane.showMessageDialog(null, "Please fill all fields!");
    return;
    }
    try {
    System.out.println("IMAGE PATH SAVED: " + imagePath);
    ConnectXamppSQL.Insert("addrecord")
        .set("Student_Id", studentId)
        .set("Student_Name", studentName)
        .set("Grade_Section", gradeSection)
        .set("Offense_Type", offense)
        .set("Days_of_Suspension", suspension)
        .set("Offense_Classification", offenseC)
        .set("Date_of_Incident", sqlDate)
        .set("image_path", imagePath)
        .execute();
         

    javax.swing.JOptionPane.showMessageDialog(null, "Record Saved!");
    new frmDashboardAdmin().setVisible(true);
    this.dispose();
    }
    catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, e.getMessage());
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtStudentIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentIdKeyTyped
    if(!Character.isDigit(evt.getKeyChar())){
    evt.consume();
    }
    }//GEN-LAST:event_txtStudentIdKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    JFileChooser file = new JFileChooser();
    file.setCurrentDirectory(new File(System.getProperty("user.home")));
    FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image","jpg","gif","png","webp");
    file.addChoosableFileFilter(filter);
    int output = file.showOpenDialog(file);
    if(output==JFileChooser.APPROVE_OPTION){
    File  selectFile = file.getSelectedFile();
    String fileName = System.currentTimeMillis() + "_" + selectFile.getName();
    String newPath = "images/" + fileName;

    File dest = new File(newPath);


    try {
    java.nio.file.Files.copy(
    selectFile.toPath(),
    dest.toPath(),
    java.nio.file.StandardCopyOption.REPLACE_EXISTING);
    } 
    catch (Exception e) {
    e.printStackTrace();
    }
    
    imagePath = newPath;
    jLabel12.setIcon(imageAdjust(newPath, null));
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     frmMonthlyRecord DA = new frmMonthlyRecord();
     DA.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     frmAddRecord ss = new frmAddRecord();
     ss.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        logins d = new logins();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private ImageIcon imageAdjust(String path, byte[] pic){
    ImageIcon myImage = null;
    if(path !=null){
    myImage = new ImageIcon(path);
    }
    else{
    myImage = new ImageIcon(pic);
    }
    
    Image img = myImage.getImage();
    Image newImage = img.getScaledInstance(jLabel12.getWidth(), jLabel12.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon icon = new ImageIcon(newImage);
    return icon;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbGrade;
    private javax.swing.JComboBox<String> cmbOffense;
    private javax.swing.JComboBox<String> cmbOffenseC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblbackg;
    private javax.swing.JSpinner spnDate;
    private javax.swing.JSpinner spnSuspension;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
